[package]
name = "rust_rest"
version = "0.1.0"
edition = "2021"
default-run = "rust_rest"

[dependencies]
axum = "0.6.2"
bb8 = "0.8.0"
bb8-postgres = "0.8.1"
dotenvy = "0.15.6"
rand = "0.8.5"
refinery = { version = "0.8", features = ["tokio-postgres"]}
serde = { version = "1.0", features = ["derive"] } 
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.15", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
tower = { version = "0.4", features = ["util"] }
hyper = { version = "0.14", features = ["full"] }
